openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000/v1
    description: Internal staging server for testing
  - url: https://api.shop3.com
    description: Production server

paths:

  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - users
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/User'
    post:
      summary: Creates a user.
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses: 
        '201':
          description: Created
      security:
        - bearerAuth: []

  /users/{userId}:
    get:
      summary: Returns a user by ID.22
      tags:
        - store
      parameters:
        - name: userId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK
      security:
        - bearerAuth: []

components:

  schemas:

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT