openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API (User)
  version: 1.0.0
servers:
  - url: https://shop3-api.codingbombs.com:3001
  - url: http://127.0.0.1:3000

paths:
  /test/user:
    post:
      summary: A test API
      tags:
        - Test
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
