openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API (Common)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000

paths:
  /api-common/v1/register/email:
    post:
      summary: Register a new user by email
      tags:
        - Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - verificationCode
                - password
                - passwordConfirm
              properties:
                email:
                  type: string
                  format: email
                  example: johnsm@gmail.com
                verificationCode:
                  type: string
                  example: '123456'
                password:
                  type: string
                  example: securePassword
                passwordConfirm:
                  type: string
                  example: securePassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/register/phone:
    post:
      summary: Register a new user by phone number
      tags:
        - Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - verificationCode
                - password
                - passwordConfirm
              properties:
                phone:
                  type: string
                  example: '0123456789'
                verificationCode:
                  type: string
                  example: '123456'
                password:
                  type: string
                  example: securePassword
                passwordConfirm:
                  type: string
                  example: securePassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/is_login:
    get:
      summary: Check if user is logged in or not
      tags:
        - Authentication
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      uuid:
                        type: string
                        format: uuid
                        example: 69b6207f-600f-4188-9a7b-569f0d9e476b
                      userGroupId:
                        type: integer
                        example: 2
                      iat:
                        type: integer
                        example: 1715867409
                      exp:
                        type: integer
                        example: 1715953809

        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/me:
    get:
      summary: Get the current user data
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON object of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/refresh_token:
    post:
      summary: Refresh the access token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzEyODA4ODA2LCJleHAiOjE3MTU0MDA4MDZ9.q5nQpO8LJjAsR0DGZwGqpcpAT1nBQQ73XvsiXckLAOo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzEyODA4OTc2LCJleHAiOjE3MTI4MDk4NzZ9.n1h2ue1hn8j5ZfSwtqtpOokDyMp8dPEu-K5Luw4aiwY'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api-common/v1/auth/login/email:
    post:
      summary: Login by email
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: johnsm@gmail.com
                password:
                  type: string
                  example: securePassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/login/phone:
    post:
      summary: Login by phone
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - password
              properties:
                phone:
                  type: string
                  example: '0123456789'
                password:
                  type: string
                  example: securePassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/reset_password/email:
    post:
      summary: Reset password by email
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - passwordConfirm
                - verificationCode
              properties:
                email:
                  type: string
                  format: email
                  example: johnsm@gmail.com
                password:
                  type: string
                  example: securePassword
                passwordConfirm:
                  type: string
                  example: securePassword
                verificationCode:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/reset_password/phone:
    post:
      summary: Reset password by phone
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - password
                - passwordConfirm
                - verificationCode
              properties:
                phone:
                  type: string
                  example: '0123456789'
                password:
                  type: string
                  example: securePassword
                passwordConfirm:
                  type: string
                  example: securePassword
                verificationCode:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/generate_otp/email:
    post:
      summary: Generate OTP code by email
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: 'johnsm@gmail.com'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/generate_otp/phone:
    post:
      summary: Generate OTP code by phone
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
              properties:
                phone:
                  type: string
                  example: '0123456789'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/confirm_otp:
    post:
      summary: Confirm if the OTP code is valid
      description: |
        1. `reciever` parameter can be an email address or a phone number
        2. `remove` parameter is optional, send it as `true` if you want to remove that OTP after the confirmation
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - receiver
                - code
              properties:
                receiver:
                  type: string
                  example: johnsm@gmail.com
                code:
                  type: string
                  example: 123456
                remove:
                  type: boolean
                  default: false
                  example: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/auth/logout:
    post:
      summary: Logout
      tags:
        - Authentication
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/languages:
    get:
      summary: Get all languages
      tags:
        - Languages
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LanguageResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-common/v1/currencies:
    get:
      summary: Get all currencies
      tags:
        - Currencies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CurrencyResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzEyODA4OTc2LCJleHAiOjE3MTI4MDk4NzZ9.n1h2ue1hn8j5ZfSwtqtpOokDyMp8dPEu-K5Luw4aiwY'
        refreshToken:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzEyODA4ODA2LCJleHAiOjE3MTU0MDA4MDZ9.q5nQpO8LJjAsR0DGZwGqpcpAT1nBQQ73XvsiXckLAOo'

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        uuid:
          type: string
          format: uuid
          example: 6252290c-1a4e-4556-a8cd-e3e32e316fd7
        name:
          type: string
          example: John Smith
        email:
          type: string
          example: johnsm@gmail.com
        phone:
          type: string
          example: '0123456789'
        avatar:
          type: string
          example: https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg
        gender:
          type: integer
          example: 1
        dob:
          type: string
          format: date-time
        languageId:
          type: integer
          example: 1
        currencyId:
          type: integer
          example: 1
        shopId:
          type: integer
          example: 1
        subscribeMailingList:
          type: boolean
        isPhoneValidated:
          type: boolean
        isEmailValidated:
          type: boolean
        isActive:
          type: boolean
        lastLogin:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    LanguageResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: English
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time


    CurrencyResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: U.S. dollar
        code:
          type: string
          example: USD
        symbol:
          type: string
          example: $
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
