openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API (Common)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000/api/v1

paths:
  /test/common:
    post:
      summary: A test API
      tags:
        - Test
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
