openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API (Administrator)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000

paths:
  /api-admin/v1/languages:
    get:
      summary: Get all languages
      tags:
        - Languages
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Names to filter by.
          required: false
          style: form
          schema:
            type: string
        - name: page
          in: query
          description: The page number for paginated results.
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: Maximum number of results to return.
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: List of Languages
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LanguageResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    post:
      summary: Create a language.
      tags:
        - Languages
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: English
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageResponse'
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '500':
          description: Internal Server Error

  /api-admin/v1/languages/:id:
    get:
      summary: Get a language
      tags:
        - Languages
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Language Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detail of a language
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/LanguageResponse'
        '400':
          description: Bad Request
        '404':
          description: Language not found
        '500':
          description: Internal Server Error

    put:
      summary: Update a language.
      tags:
        - Languages
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Language Id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: English
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageResponse'
        '400':
          description: Bad Request
        '404':
          description: Language not found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error

    delete:
      summary: Delete a language
      tags:
        - Languages
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Language Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad Request
        '404':
          description: Language not found
        '500':
          description: Internal Server Error

  /api-admin/v1/currencies:
    get:
      summary: Get all currencies
      tags:
        - Currencies
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Names to filter by.
          required: false
          style: form
          schema:
            type: string
        - name: code
          in: query
          description: Codes to filter by.
          required: false
          style: form
          schema:
            type: string
        - name: page
          in: query
          description: The page number for paginated results.
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: Maximum number of results to return.
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: List of Currencies
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CurrencyResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    post:
      summary: Create a currency.
      tags:
        - Currencies
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - code
                - symbol
              properties:
                name:
                  type: string
                  example: U.S. dollar
                code:
                  type: string
                  example: USD
                symbol:
                  type: string
                  example: $
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyResponse'
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '500':
          description: Internal Server Error

  /api-admin/v1/currencies/:id:
    get:
      summary: Get a currency
      tags:
        - Currencies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Currency Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detail of a currency
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/CurrencyResponse'
        '400':
          description: Bad Request
        '404':
          description: Currency not found
        '500':
          description: Internal Server Error

    put:
      summary: Update a currency.
      tags:
        - Currencies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Currency Id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - code
                - symbol
              properties:
                name:
                  type: string
                  example: U.S. dollar
                code:
                  type: string
                  example: USD
                symbol:
                  type: string
                  example: $
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyResponse'
        '400':
          description: Bad Request
        '404':
          description: Currency not found
        '409':
          description: Conflict
        '500':
          description: Internal Server Error

    delete:
      summary: Delete a currency
      tags:
        - Currencies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Currency Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deleted
        '400':
          description: Bad Request
        '404':
          description: Currency not found
        '500':
          description: Internal Server Error

  /api-admin/v1/shops:
    get:
      summary: Get all shops
      description: Show shops that have been submitted
      tags:
        - Shops
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of Shops
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ShopResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-admin/v1/shops/:id:
    get:
      summary: Get a shop
      tags:
        - Shops
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Shop Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Detail of a shop
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/ShopResponse'
        '400':
          description: Bad Request
        '404':
          description: Shop not found
        '500':
          description: Internal Server Error

  /api-admin/v1/shops/:id/verify:
    post:
      summary: Verify a Shop
      tags:
        - Shops
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Shop Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Verified
        '400':
          description: Bad Request
        '404':
          description: Shop not found
        '500':
          description: Internal Server Error

  /api-admin/v1/shops/:id/activate:
    post:
      summary: Activate a Shop
      tags:
        - Shops
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Shop Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Activated
        '400':
          description: Bad Request
        '404':
          description: Shop not found
        '500':
          description: Internal Server Error

  /api-admin/v1/shops/:id/deactivate:
    post:
      summary: Deactivate a Shop
      tags:
        - Shops
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Shop Id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Deactivated
        '400':
          description: Bad Request
        '404':
          description: Shop not found
        '500':
          description: Internal Server Error

components:
  schemas:
    LanguageResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: English
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CurrencyResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: U.S. dollar
        code:
          type: string
          example: USD
        symbol:
          type: string
          example: $
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ShopResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        sellerBusinessTypeId:
          type: integer
          example: 1
        shopName:
          type: string
          example: 'My Shop'
        userId:
          type: integer
          example: 1
        email:
          type: string
          format: email
          example: johnsm@gmail.com
        phone:
          type: string
          format: phone
          example: '0123456789'
        subscribeMailingList:
          type: boolean
          example: true
        householdBusinessRegistrationDocument1:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        householdBusinessRegistrationDocument2:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        householdBusinessRegistrationDocument3:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        householdBusinessName:
          type: string
          example: 'My Company'
        householdBusinessRegistrationNumber:
          type: string
          example: 'AB100000'
        householdBusinessOwnerName:
          type: string
          example: 'John Smith'
        householdBusinessOwnerIdNumber:
          type: string
          example: '123456789'
        individualIdentityCardFront:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        individualIdentityCardBack:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        individualIdentityCardNumber:
          type: string
          example: '123456789'
        individualOwnerDob:
          type: string
          format: date-time
        individualBusinessOwnerName:
          type: string
          example: 'John Smith'
        individualResidentialAddress:
          type: string
          example: '206 Lorem Ipsum st.'
        individualProductCategoryId:
          type: integer
          example: 1
        corporateCompanyRegistrationDocument1:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        corporateCompanyRegistrationDocument2:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        corporateCompanyRegistrationDocument3:
          type: string
          example: 'https://storage.googleapis.com/dummy/file_44103033-d9f4-4933-bacc-11701c90e58a.jpg'
        corporateCompanyName:
          type: string
          example: 'My Company'
        corporateEnterpiseCodeNumber:
          type: string
          example: 'AB100000'
        isSubmitted:
          type: boolean
          example: true
        isVerified:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
