openapi: 3.0.0
info:
  title: Shop3 API
  description: Documentation for Shop3 API (Seller)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000

paths:
  /api-seller/v1/categories:
    get:
      summary: Get all categories
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - name: parentId
          in: query
          description: ID of the parent category
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A list of categories
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-seller/v1/categories/:id/attributes:
    get:
      summary: Get all attributes of the category
      tags:
        - Categories
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the category to get attributes
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of attributes of the category
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 1
                        name:
                          type: string
                          example: 'Season'
                        attributeValues:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                                format: int32
                                example: 1
                              name:
                                type: string
                                example: 'Spring'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-seller/v1/brands:
    get:
      summary: Get all brands
      tags:
        - Brands
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of brands
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

    post:
      summary: Create a new brand
      tags:
        - Brands
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: New Brand
                description:
                  type: string
                  example: Dummy
      responses:
        '201':
          description: The newly created brand
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-seller/v1/sellers/business_types:
    get:
      summary: Get a list of business types
      tags:
        - Sellers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A JSON array of business types
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/SellerBusinessTypesResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /api-seller/v1/sellers/logistics_services/subscribe:
    post:
      summary: Subscribe to a shipping service
      tags:
        - Logistics Services
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - serviceId
              properties:
                serviceId:
                  type: integer
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrueResponse'
        '400':
          description: Bad Request
        '404':
          description: Logistics service was not found
        '500':
          description: Internal Server Error

  /api-seller/v1/sellers/logistics_services/unsubscribe:
    post:
      summary: Unsubscribe to a shipping service
      tags:
        - Logistics Services
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - serviceId
              properties:
                serviceId:
                  type: integer
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrueResponse'
        '400':
          description: Bad Request
        '404':
          description: Logistics service was not found
        '500':
          description: Internal Server Error

  /api-seller/v1/sellers/logistics_services/estimate_shipping_fee:
    post:
      summary: Estimate shipping fee
      tags:
        - Logistics Services
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - serviceId
                - weight
                - width
                - height
                - length
              properties:
                serviceId:
                  type: integer
                  example: 1
                weight:
                  type: integer
                  example: 1000
                width:
                  type: integer
                  example: 20
                height:
                  type: integer
                  example: 20
                length:
                  type: integer
                  example: 20
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimatedShippingFee:
                    type: number
                    format: float
                    example: 10000
        '400':
          description: Bad Request
        '404':
          description: Logistics service was not found
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TrueResponse:
      type: object
      properties:
        data:
          type: object
          example: true

    SellerBusinessTypesResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: Household
          description:
            type: string
            example: Dummy
